language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

services: mysql

before_script:
  - mysql -e 'CREATE DATABASE test;'
  - mysql test < voj.sql

script: 
  - mvn test -f web/pom.xml
  - mvn test -f judger/pom.xml

after_script:
  - mysql -e 'DROP DATABASE test;'
