
# # version: "{branch} {build}"

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files\Java\jdk9

services:
  - mysql

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - set PATH=%PATH%;C:\Program Files\MySql\MySQL Server 5.7\bin;C:\cygwin64\bin
  - net user /add "hzxie" "@AppVeyor"
# Fix bug for mkdir in AppVeyor
  - del "C:\Program Files\Git\usr\bin\mkdir.exe"
# Fix path error on JNI headers
  - copy "C:\Program Files\Java\jdk1.8.0\include\win32\jni_md.h" "C:\Program Files\Java\jdk1.8.0\include\jni_md.h"
  - copy "C:\Program Files\Java\jdk1.8.0\include\win32\jawt_md.h" "C:\Program Files\Java\jdk1.8.0\include\jawt_md.h"
  - copy "C:\Program Files\Java\jdk9\include\win32\jni_md.h" "C:\Program Files\Java\jdk9\include\jni_md.h"
  - copy "C:\Program Files\Java\jdk9\include\win32\jawt_md.h" "C:\Program Files\Java\jdk9\include\jawt_md.h"
# Setup test environment for Windows
  - copy "judger\src\test\resources\voj-test-windows.properties" "judger\src\test\resources\voj-test.properties"

build: off

before_test:
  - mysql -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('');" --user=root --password=Password12!
  - mysql -e "CREATE DATABASE test;" --user=root
  - mysql test < voj.sql --user=root

test_script:
  - mvn test -f web\pom.xml --batch-mode
  # Disable tests for judger because of crash of JVM
  # - mvn test -f judger\pom.xml --batch-mode

after_test:
  - mysql -e "DROP DATABASE test;" --user=root

on_finish:
  - ps: $blockRdp = $false; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

matrix:
  fast_finish: true

cache:
  - C:\maven\
  - C:\Users\appveyor\.m2